### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by Illusion4** [skyf0l/adb-ssl-unpinning#2]
PS C:\Users\Home\Downloads\platform-tools_r34.0.4-windows\platform-tools> python C:\Users\Home\Downloads\adb-ssl-unpinning-main\adb-ssl-unpinning-main\adb-ssl-unpinning.py 127.0.0.1:21503 com.supercell.brawlstars
Pulling /data/app/com.supercell.brawlstars-0LcR7gT70r6XtP7oYFRp5Q==/base.apk...
Pulling /data/app/com.supercell.brawlstars-0LcR7gT70r6XtP7oYFRp5Q==/split_config.arm64_v8a.apk...
Pulling /data/app/com.supercell.brawlstars-0LcR7gT70r6XtP7oYFRp5Q==/split_config.uk.apk...
Pulling /data/app/com.supercell.brawlstars-0LcR7gT70r6XtP7oYFRp5Q==/split_config.xhdpi.apk...
Pulling /data/app/com.supercell.brawlstars-0LcR7gT70r6XtP7oYFRp5Q==/split_googleplay_asset_pack.apk...
Traceback (most recent call last):
  File "C:\Users\Home\Downloads\adb-ssl-unpinning-main\adb-ssl-unpinning-main\adb-ssl-unpinning.py", line 132, in <module>
    patch_package(device, package_name)
  File "C:\Users\Home\Downloads\adb-ssl-unpinning-main\adb-ssl-unpinning-main\adb-ssl-unpinning.py", line 88, in patch_package
    sp.run(["java", "-jar", APKTOOL, "d", apk_path, "-o", unpacked_apk_path, "-s"])
  File "C:\Users\Home\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Home\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by skyf0l** [comment]
Hello @Illusion4, it seems that you don't have java installed, I'll probably make a docker version later to avoid installing java.
